### ISSUE TITLE
VSCode menu is hard to read in Summer Day

### ISSUE THREAD

**Issue by khuongduybui** [terra-theme/vscode#17]
Pale purple on pale blue gray in Summer Day is hard to read.
![image](https://user-images.githubusercontent.com/831343/203329576-205a7c79-3dd4-44d6-8b43-0806a55ddc52.png)
Also notice how the word "Explorer" is completely invisible.

On contrary, mid-yellow on very dark blue gray in Summar Night is very readable.
![image](https://user-images.githubusercontent.com/831343/203329859-fd8fdea3-33d1-4f9c-b684-d25cede14c44.png)

**Comment by nikbrunner** [comment]
Okay thank you. I will try to fix it this week.
