### ISSUE TITLE
File names in VS Code Summer Night now hard to read

### ISSUE THREAD

**Issue by khuongduybui** [terra-theme/vscode#20]
It used to be okay but now after the latest update it's very hard to read
![image](https://user-images.githubusercontent.com/831343/204114812-d41a3bae-2d0b-4860-9d71-a78604e67f9c.png)

**Comment by nikbrunner** [comment]
Thank you for reporting :)
I wanted to fade out the sidebar fg colors, but I may overdid it a bit.
I pushed out a new release which should still fade out the sidebar fg colors a little bit, but not so much.

**Comment by khuongduybui** [comment]
> Now it should be live

Thank you very much. I'll check it out asap.
