### ISSUE TITLE
Poor visibility for search-result marker

### ISSUE THREAD

**Issue by nikbrunner** [terra-theme/vscode#7]
Terra Spring Night
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/46924729/199506310-2b594118-7f92-40fc-91a8-563f227dfc05.png">

Github Dark Default
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/46924729/199506392-8ac1edcf-1483-4977-90a8-f962a4daf505.png">

**Comment by rcrooks** [comment]
I agree with this comment. Overall, I think Terra-Spring is a really outstanding theme, but I would love a little more contrast between the background of selected text and search matches, and the general background. 
Thanks for considering.

**Comment by nikbrunner** [comment]
I agree, and I will consider your Feedback when fixing this issue :)
