### ISSUE TITLE
White on white in Python / Spring Day

### ISSUE THREAD

**Issue by khuongduybui** [terra-theme/vscode#8]
The variables look fine in Spring Night (white on black) but in Spring Day it's white on white.

![image](https://user-images.githubusercontent.com/831343/202031337-5b419af2-6d12-44f7-93e7-985870c34e1f.png)
![image](https://user-images.githubusercontent.com/831343/202031368-02279277-c87b-4e17-95d2-6bd1a2c74d8e.png)

**Comment by nikbrunner** [comment]
Thank you for your report. Fixed with #11

**Comment by khuongduybui** [comment]
Thanks for quick fix. Will you publish the update to vs market? I can't wait to see!

**Comment by nikbrunner** [comment]
> Thanks for quick fix. Will you publish the update to vs market? I can't wait to see! 

Already live. :)

**Comment by khuongduybui** [comment]
fantastic
